VAGRANTFILE_API_VERSION = "2"
BOX_NAME = "centos/7"
PROVIDER = "virtualbox"
MEMORY = "2048"
CPUS = 2

Vagrant.configure("2") do |config|
    config.vm.box = BOX_NAME
    config.vm.provider PROVIDER do |vb|
       vb.memory = MEMORY
       vb.cpus = CPUS
    end

    config.vm.define "rancher" do |rancher|
        rancher.vm.network :private_network, ip: "172.16.10.1"
        rancher.vm.hostname = "rancher"
        rancher.vm.network "forwarded_port", guest: 8080, host: 8080
        rancher.vm.network "forwarded_port", guest: 8443, host: 8443
        rancher.vm.provider PROVIDER do |vb|
            vb.name = "rancher"
        end
        rancher.vm.provision "shell", path: "../scripts/install-docker.sh"
        rancher.vm.provision "shell", path: "../scripts/install-rancher.sh"
        rancher.vm.provision "shell", path: "../scripts/install-rke.sh"
        rancher.vm.provision "shell", path: "../scripts/install-kubectl.sh"
        rancher.vm.provision "file", source: "../cluster.yml", destination: "~vagrant/cluster.yml"
        rancher.vm.provision "file", source: "~/.ssh/nghia.nguyen2.sts", destination: "~vagrant/.ssh/nghia.nguyen2.sts"
        rancher.vm.provision "file", source: "~/.ssh/nghia.nguyen2.sts.pub", destination: "~vagrant/.ssh/nghia.nguyen2.sts.pub"
        rancher.vm.provision "shell", inline: <<-SHELL
          cat ~vagrant/.ssh/nghia.nguyen2.sts.pub >> /home/vagrant/.ssh/authorized_keys
        SHELL
    end

    config.vm.define "manager" do |manager|
        manager.vm.network :private_network, ip: "172.16.10.2"
        manager.vm.hostname = "manager"
        manager.vm.provider PROVIDER do |vb|
            vb.name = "manager"
        end
        manager.vm.provision "shell", path: "../scripts/install-docker.sh"
        manager.vm.provision "file", source: "~/.ssh/nghia.nguyen2.sts.pub", destination: "~vagrant/.ssh/nghia.nguyen2.sts.pub"
        manager.vm.provision "shell", inline: <<-SHELL
          cat ~vagrant/.ssh/nghia.nguyen2.sts.pub >> /home/vagrant/.ssh/authorized_keys
        SHELL
    end

    config.vm.define "worker" do |worker|
        worker.vm.network :private_network, ip: "172.16.10.3"
        worker.vm.hostname = "worker"
        worker.vm.provider PROVIDER do |vb|
            vb.name = "worker"
        end
        worker.vm.provision "shell", path: "../scripts/install-docker.sh"
        worker.vm.provision "file", source: "~/.ssh/nghia.nguyen2.sts.pub", destination: "~vagrant/.ssh/nghia.nguyen2.sts.pub"
        worker.vm.provision "shell", inline: <<-SHELL
          cat ~vagrant/.ssh/nghia.nguyen2.sts.pub >> /home/vagrant/.ssh/authorized_keys
        SHELL
    end
end
